#Ai Agent Time

from dotenv import load_dotenv
import requests
import os
from datetime import datetime

# Load biến môi trường
load_dotenv()
url = os.getenv('URL_OLLAMA')

def AgentTime(): 
    """
        Generates an AI response that describes the current time in a natural form.
        This function sends a prompt to the AI ​​model (e.g. gemma:2b via Ollama)
        to ask it to parse the current system time and return a natural response that describes the date and time.
        Returns:
        str: The response generated by the AI ​​model, or an error message if something goes wrong.
    """
    prompt = (
        "You are a smart assistant. "
        f"Current date and time ({datetime.now().isoformat()}), "
        "respond with a natural sentence stating the date and time."
    )
    try:
        response = requests.post(url, json={
            "model": "gemma:2b", # Load model gemma:2b
            "prompt": prompt,
            "stream": False
        })
        response.raise_for_status()  # Gây lỗi nếu HTTP không 200
        return response.json().get("response", "Error: No response from the model.")
    except Exception as e:
        return f"Error:  {str(e)}"


print(AgentTime())